"""
app/db/models/jobs.py
──────────────────────
ORM model for the `jobs` table.

A Job represents a single upload session submitted by the user.
- One job contains 1–5 Document records.
- The job's `status` is the aggregate health of all its documents.
- `metadata` JSONB is a free-form field for future extensibility
  (e.g., user ID, batch tags).
"""

import uuid
from datetime import datetime

from sqlalchemy import JSON, CheckConstraint, DateTime, Integer, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.models.base import Base


class Job(Base):
    __tablename__ = "jobs"

    # Primary key — UUID generated by Python (not the DB) so we know the ID
    # before the INSERT completes, which is useful for building file paths.
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # Reflects the job's lifecycle.  Values mirror the CHECK constraint in init.sql.
    status: Mapped[str] = mapped_column(
        String,
        nullable=False,
        default="PENDING",
    )

    # Number of files submitted in this job (set at ingestion time).
    document_count: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
    )

    # Free-form JSON metadata (future-proofing; not read by V1 pipeline logic).
    metadata_: Mapped[dict | None] = mapped_column(
        "metadata",   # column name in PostgreSQL is `metadata`
        JSON,
        nullable=True,
    )

    # Timestamps — func.now() asks the DB for its current time, which is TZ-aware.
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    # SQLAlchemy-level relationship (not a DB column) — lets us write job.documents
    # to get a list of all Document objects for this job.
    # back_populates keeps both sides in sync in memory.
    documents: Mapped[list["Document"]] = relationship(  # noqa: F821
        "Document",
        back_populates="job",
        cascade="all, delete-orphan",
    )

    # Enforce the allowed status values at the ORM/DB boundary.
    __table_args__ = (
        CheckConstraint(
            "status IN ('PENDING','INGESTED','PARTIAL_FAILURE','EXTRACTING','DONE','FAILED')",
            name="ck_jobs_status",
        ),
    )
